shared:
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>

development:
  database: incubit_dev

test:
  database: incubit_dev

staging:
  database: incubit_stg

production:
  database: <%= ENV.fetch('DB') { } %>
